from PyQt6.QtCore import QCoreApplication, QMetaObject, QRect,Qt
from PyQt6.QtGui import QIcon, QPixmap, QFont
from PyQt6.QtWidgets import QHBoxLayout, QLabel, QLineEdit, QPushButton, QVBoxLayout, QWidget

class Ui_loginForm(object):
    def setupUi(self, loginForm):
        if not loginForm.objectName():
            loginForm.setObjectName(u"loginForm")
        loginForm.resize(430, 160)
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.UserAvailable))
        loginForm.setWindowIcon(icon)
        self.verticalLayoutWidget = QWidget(loginForm)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(210, 20, 201, 71))
        self.lineLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.lineLayout.setObjectName(u"lineLayout")
        self.lineLayout.setContentsMargins(0, 0, 0, 0)
        self.user_input = QLineEdit(self.verticalLayoutWidget)
        self.user_input.setObjectName(u"user_input")
        self.lineLayout.addWidget(self.user_input)
        self.pw_input = QLineEdit(self.verticalLayoutWidget)
        self.pw_input.setObjectName(u"pw_input")
        self.pw_input.setEchoMode(QLineEdit.EchoMode.Password)
        self.lineLayout.addWidget(self.pw_input)
        self.verticalLayoutWidget_2 = QWidget(loginForm)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(140, 20, 61, 71))
        self.labelLayout = QVBoxLayout(self.verticalLayoutWidget_2)
        self.labelLayout.setObjectName(u"labelLayout")
        self.labelLayout.setContentsMargins(0, 0, 0, 0)
        self.userLabel = QLabel(self.verticalLayoutWidget_2)
        self.userLabel.setObjectName(u"userLabel")
        font = QFont()
        font.setPointSize(10)
        self.userLabel.setFont(font)
        self.labelLayout.addWidget(self.userLabel, 0, Qt.AlignmentFlag.AlignLeft)
        self.passLabel = QLabel(self.verticalLayoutWidget_2)
        self.passLabel.setObjectName(u"passLabel")
        self.passLabel.setFont(font)
        self.labelLayout.addWidget(self.passLabel, 0, Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayoutWidget = QWidget(loginForm)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(140, 90, 271, 58))
        self.buttonLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.buttonLayout.setObjectName(u"buttonLayout")
        self.buttonLayout.setContentsMargins(0, 0, 0, 0)
        self.registerButton = QPushButton(self.horizontalLayoutWidget)
        self.registerButton.setObjectName(u"registerButton")
        self.buttonLayout.addWidget(self.registerButton)
        self.loginButton = QPushButton(self.horizontalLayoutWidget)
        self.loginButton.setObjectName(u"loginButton")
        self.buttonLayout.addWidget(self.loginButton)
        self.statusLabel = QLabel(loginForm)
        self.statusLabel.setObjectName(u"statusLabel")
        self.statusLabel.setGeometry(QRect(141, 137, 56, 16))
        self.statusLabel.setFont(font)
        self.resultLabel = QLabel(loginForm)
        self.resultLabel.setObjectName(u"resultLabel")
        self.resultLabel.setStyleSheet("color: red;")
        self.resultLabel.setGeometry(QRect(190, 137, 221, 16))
        self.resultLabel.setFont(font)
        self.imageLogo = QPixmap("image.png")
        self.imagelabel = QLabel(loginForm)
        self.imagelabel.setPixmap(self.imageLogo)
        self.imagelabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.imagelabel.setObjectName(u"imagelabel")
        self.imagelabel.setGeometry(QRect(10, 15, 111, 111))
        self.retranslateUi(loginForm)
        QMetaObject.connectSlotsByName(loginForm)
    # setupUi

    def retranslateUi(self, loginForm):
        loginForm.setWindowTitle(QCoreApplication.translate("loginForm", u"Login", None))
        self.user_input.setText("")
        self.pw_input.setPlaceholderText("")
        self.userLabel.setText(QCoreApplication.translate("loginForm", u"Username", None))
        self.passLabel.setText(QCoreApplication.translate("loginForm", u"Password", None))
        self.registerButton.setText(QCoreApplication.translate("loginForm", u"Register", None))
        self.loginButton.setText(QCoreApplication.translate("loginForm", u"Login", None))
        self.statusLabel.setText(QCoreApplication.translate("loginForm", u"Status :", None))
        self.resultLabel.setText(QCoreApplication.translate("loginForm", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
        self.imagelabel.setText("")
    # retranslateUi

