from PyQt6.QtCore import QCoreApplication, QMetaObject, QRect, QSize
from PyQt6.QtGui import QFont, QIcon
from PyQt6.QtWidgets import (QFrame, QLabel, QLineEdit, QPushButton, QTableWidget,
                             QStatusBar, QTabWidget, QTextEdit, QWidget, QColumnView)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1024, 768)
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.FolderNew))
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frameBar = QFrame(self.centralwidget)
        self.frameBar.setObjectName(u"frameBar")
        self.frameBar.setGeometry(QRect(0, 0, 1024, 50))
        self.frameBar.setFrameShape(QFrame.Shape.StyledPanel)
        self.frameBar.setFrameShadow(QFrame.Shadow.Raised)
        self.newButton = QPushButton(self.frameBar)
        self.newButton.setObjectName(u"newButton")
        self.newButton.setGeometry(QRect(0, 0, 60, 50))
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentNew))
        self.newButton.setIcon(icon1)
        self.newButton.setIconSize(QSize(20, 20))
        self.saveButton = QPushButton(self.frameBar)
        self.saveButton.setObjectName(u"saveButton")
        self.saveButton.setGeometry(QRect(60, 0, 60, 50))
        icon2 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentSave))
        self.saveButton.setIcon(icon2)
        self.saveButton.setIconSize(QSize(20, 20))
        self.editButton = QPushButton(self.frameBar)
        self.editButton.setObjectName(u"editButton")
        self.editButton.setGeometry(QRect(120, 0, 60, 50))
        icon3 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.MailMessageNew))
        self.editButton.setIcon(icon3)
        self.editButton.setIconSize(QSize(20, 20))
        self.cancelButton = QPushButton(self.frameBar)
        self.cancelButton.setObjectName(u"cancelButton")
        self.cancelButton.setGeometry(QRect(180, 0, 60, 50))
        icon4 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ApplicationExit))
        self.cancelButton.setIcon(icon4)
        self.cancelButton.setIconSize(QSize(20, 20))
        self.helpButton = QPushButton(self.frameBar)
        self.helpButton.setObjectName(u"helpButton")
        self.helpButton.setGeometry(QRect(950, 0, 60, 50))
        icon5 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.HelpFaq))
        self.helpButton.setIcon(icon5)
        self.helpButton.setIconSize(QSize(20, 20))
        self.printButton = QPushButton(self.frameBar)
        self.printButton.setObjectName(u"printButton")
        self.printButton.setGeometry(QRect(240, 0, 60, 50))
        icon6 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentPrint))
        self.printButton.setIcon(icon6)
        self.printButton.setIconSize(QSize(20, 20))
        self.frameInput = QFrame(self.centralwidget)
        self.frameInput.setObjectName(u"frameInput")
        self.frameInput.setGeometry(QRect(0, 50, 1024, 211))
        self.frameInput.setAutoFillBackground(False)
        self.frameInput.setFrameShape(QFrame.Shape.StyledPanel)
        self.frameInput.setFrameShadow(QFrame.Shadow.Raised)
        self.labelOwner = QLabel(self.frameInput)
        self.labelOwner.setObjectName(u"labelOwner")
        self.labelOwner.setGeometry(QRect(10, 15, 131, 16))
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(10)
        font.setBold(True)
        self.labelOwner.setFont(font)
        self.labelOp = QLabel(self.frameInput)
        self.labelOp.setObjectName(u"labelOp")
        self.labelOp.setGeometry(QRect(10, 45, 131, 16))
        self.labelOp.setFont(font)
        self.labelOrder = QLabel(self.frameInput)
        self.labelOrder.setObjectName(u"labelOrder")
        self.labelOrder.setGeometry(QRect(10, 105, 131, 16))
        self.labelOrder.setFont(font)
        self.labelCorp = QLabel(self.frameInput)
        self.labelCorp.setObjectName(u"labelCorp")
        self.labelCorp.setGeometry(QRect(10, 75, 131, 16))
        self.labelCorp.setFont(font)
        self.labelexp = QLabel(self.frameInput)
        self.labelexp.setObjectName(u"labelexp")
        self.labelexp.setGeometry(QRect(10, 135, 131, 16))
        self.labelexp.setFont(font)
        self.opownerLine = QLineEdit(self.frameInput)
        self.opownerLine.setObjectName(u"opownerLine")
        self.opownerLine.setGeometry(QRect(120, 10, 241, 22))
        self.opnameLine = QLineEdit(self.frameInput)
        self.opnameLine.setObjectName(u"opnameLine")
        self.opnameLine.setGeometry(QRect(120, 40, 241, 22))
        self.orderLine = QLineEdit(self.frameInput)
        self.orderLine.setObjectName(u"orderLine")
        self.orderLine.setGeometry(QRect(120, 100, 241, 22))
        self.corpLine = QLineEdit(self.frameInput)
        self.corpLine.setObjectName(u"corpLine")
        self.corpLine.setGeometry(QRect(120, 70, 241, 22))
        self.expEdit = QTextEdit(self.frameInput)
        self.expEdit.setObjectName(u"expEdit")
        self.expEdit.setGeometry(QRect(120, 130, 241, 71))
        self.labelDoviz = QLabel(self.frameInput)
        self.labelDoviz.setObjectName(u"labelDoviz")
        self.labelDoviz.setGeometry(QRect(400, 45, 131, 16))
        self.labelDoviz.setFont(font)
        self.opstatusLine = QLineEdit(self.frameInput)
        self.opstatusLine.setObjectName(u"opstatusLine")
        self.opstatusLine.setGeometry(QRect(510, 100, 241, 22))
        self.labelAmount = QLabel(self.frameInput)
        self.labelAmount.setObjectName(u"labelAmount")
        self.labelAmount.setGeometry(QRect(400, 15, 131, 16))
        self.labelAmount.setFont(font)
        self.labelClosedate = QLabel(self.frameInput)
        self.labelClosedate.setObjectName(u"labelClosedate")
        self.labelClosedate.setGeometry(QRect(400, 75, 131, 16))
        self.labelClosedate.setFont(font)
        self.dovizLine = QLineEdit(self.frameInput)
        self.dovizLine.setObjectName(u"dovizLine")
        self.dovizLine.setGeometry(QRect(510, 40, 241, 22))
        self.labelOpstatus = QLabel(self.frameInput)
        self.labelOpstatus.setObjectName(u"labelOpstatus")
        self.labelOpstatus.setGeometry(QRect(400, 105, 131, 16))
        self.labelOpstatus.setFont(font)
        self.amountLine = QLineEdit(self.frameInput)
        self.amountLine.setObjectName(u"amountLine")
        self.amountLine.setGeometry(QRect(510, 10, 241, 22))
        self.closedateLine = QLineEdit(self.frameInput)
        self.closedateLine.setObjectName(u"closedateLine")
        self.closedateLine.setGeometry(QRect(510, 70, 241, 22))
        self.labelPurcam = QLabel(self.frameInput)
        self.labelPurcam.setObjectName(u"labelPurcam")
        self.labelPurcam.setGeometry(QRect(424, 140, 161, 16))
        self.labelPurcam.setFont(font)
        self.labelProfit = QLabel(self.frameInput)
        self.labelProfit.setObjectName(u"labelProfit")
        self.labelProfit.setGeometry(QRect(634, 140, 91, 16))
        self.labelProfit.setFont(font)
        self.labelusdtry = QLabel(self.frameInput)
        self.labelusdtry.setObjectName(u"labelusdtry")
        self.labelusdtry.setGeometry(QRect(810, 15, 71, 16))
        self.labelusdtry.setFont(font)
        self.labeleurtry = QLabel(self.frameInput)
        self.labeleurtry.setObjectName(u"labeleurtry")
        self.labeleurtry.setGeometry(QRect(810, 40, 71, 16))
        self.labeleurtry.setFont(font)
        self.labeleurusd = QLabel(self.frameInput)
        self.labeleurusd.setObjectName(u"labeleurusd")
        self.labeleurusd.setGeometry(QRect(809, 65, 81, 16))
        self.labeleurusd.setFont(font)
        self.labeleurusd.setAutoFillBackground(False)
        self.labeleurusd.setFrameShape(QFrame.Shape.NoFrame)
        self.labeleurusd.setMidLineWidth(0)
        self.usdtry = QLabel(self.frameInput)
        self.usdtry.setObjectName(u"usdtry")
        self.usdtry.setGeometry(QRect(890, 15, 71, 16))
        self.usdtry.setFont(font)
        self.usdtry.setAutoFillBackground(True)
        self.usdtry.setFrameShape(QFrame.Shape.Box)
        self.eurusd = QLabel(self.frameInput)
        self.eurusd.setObjectName(u"eurusd")
        self.eurusd.setGeometry(QRect(889, 65, 71, 16))
        self.eurusd.setFont(font)
        self.eurusd.setAutoFillBackground(True)
        self.eurusd.setFrameShape(QFrame.Shape.Box)
        self.eurusd.setMidLineWidth(0)
        self.eurtry = QLabel(self.frameInput)
        self.eurtry.setObjectName(u"eurtry")
        self.eurtry.setGeometry(QRect(890, 40, 71, 16))
        self.eurtry.setFont(font)
        self.eurtry.setAutoFillBackground(True)
        self.eurtry.setFrameShape(QFrame.Shape.Box)
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 269, 1024, 471))
        font1 = QFont()
        font1.setPointSize(9)
        self.tabWidget.setFont(font1)
        self.tabWidget.setAutoFillBackground(False)
        self.urun_tab = QWidget()
        self.urun_tab.setObjectName(u"urun_tab")
        self.table_widget = QTableWidget(self.urun_tab)
        self.table_widget.setObjectName(u"table_widget")
        self.table_widget.setGeometry(QRect(3, 1, 1011, 441))
        self.tabWidget.addTab(self.urun_tab, "")
        self.teklif_tab = QWidget()
        self.teklif_tab.setObjectName(u"teklif_tab")
        self.tabWidget.addTab(self.teklif_tab, "")
        self.ek_tab = QWidget()
        self.ek_tab.setObjectName(u"ek_tab")
        self.tabWidget.addTab(self.ek_tab, "")
        self.durum_tab = QWidget()
        self.durum_tab.setObjectName(u"durum_tab")
        self.tabWidget.addTab(self.durum_tab, "")
        self.loadButton = QPushButton(self.centralwidget)
        self.loadButton.setObjectName(u"loadButton")
        self.loadButton.setGeometry(QRect(940, 260, 75, 31))
        icon7 = QIcon(QIcon.fromTheme(u"list-add"))
        self.loadButton.setIcon(icon7)
        self.loadButton.setIconSize(QSize(20, 20))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.newButton, self.saveButton)
        QWidget.setTabOrder(self.saveButton, self.editButton)
        QWidget.setTabOrder(self.editButton, self.cancelButton)
        QWidget.setTabOrder(self.cancelButton, self.printButton)
        QWidget.setTabOrder(self.printButton, self.helpButton)
        QWidget.setTabOrder(self.helpButton, self.opownerLine)
        QWidget.setTabOrder(self.opownerLine, self.opnameLine)
        QWidget.setTabOrder(self.opnameLine, self.opstatusLine)
        QWidget.setTabOrder(self.opstatusLine, self.corpLine)
        QWidget.setTabOrder(self.corpLine, self.orderLine)
        QWidget.setTabOrder(self.orderLine, self.expEdit)
        QWidget.setTabOrder(self.expEdit, self.dovizLine)
        QWidget.setTabOrder(self.dovizLine, self.amountLine)
        QWidget.setTabOrder(self.amountLine, self.closedateLine)
        QWidget.setTabOrder(self.closedateLine, self.tabWidget)
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.newButton.setText("")
        self.saveButton.setText("")
        self.editButton.setText("")
        self.cancelButton.setText("")
        self.helpButton.setText("")
        self.printButton.setText("")
        self.labelOwner.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:700;\">F\u0131rsat Sahibi</span></p></body></html>", None))
        self.labelOp.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>F\u0131rsat Ad\u0131</p></body></html>", None))
        self.labelOrder.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Sipari\u015f Kodu</p></body></html>", None))
        self.labelCorp.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Firma Ad\u0131</p></body></html>", None))
        self.labelexp.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>A\u00e7\u0131klama</p></body></html>", None))
        self.labelDoviz.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>D\u00f6viz Cinsi</p></body></html>", None))
        self.labelAmount.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>F\u0131rsat Tutar\u0131</p></body></html>", None))
        self.labelClosedate.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Kapan\u0131\u015f Tarihi</p></body></html>", None))
        self.labelOpstatus.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>F\u0131rsat Durumu</p></body></html>", None))
        self.labelPurcam.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Toplam Sat\u0131nalma Tutar\u0131</p></body></html>", None))
        self.labelProfit.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Kar Oran\u0131 (%)</p></body></html>", None))
        self.labelusdtry.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>USD / TRY :</p></body></html>", None))
        self.labeleurtry.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>EUR / TRY :</p></body></html>", None))
        self.labeleurusd.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>EUR / USD :</p></body></html>", None))
        self.usdtry.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>USD / TRY</p></body></html>", None))
        self.eurusd.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>EUR / USD</p></body></html>", None))
        self.eurtry.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>EUR / TRY</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.urun_tab), QCoreApplication.translate("MainWindow", u"\u00dcr\u00fcnler", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.teklif_tab), QCoreApplication.translate("MainWindow", u"Teklifler", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ek_tab), QCoreApplication.translate("MainWindow", u"Ek Bilgiler", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.durum_tab), QCoreApplication.translate("MainWindow", u"Durum \u00d6zeti", None))
        self.loadButton.setText(QCoreApplication.translate("MainWindow", u"Y\u00fckle", None))
    # retranslateUi

