from PyQt6.QtCore import QCoreApplication, QMetaObject, QRect, Qt
from PyQt6.QtGui import QFont, QIcon
from PyQt6.QtWidgets import (QHBoxLayout, QLabel, QLineEdit,
                             QPushButton, QVBoxLayout, QWidget)

class Ui_regForm(object):
    def setupUi(self, regForm):
        if not regForm.objectName():
            regForm.setObjectName(u"regForm")
        regForm.resize(362, 260)
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ContactNew))
        regForm.setWindowIcon(icon)
        self.verticalLayoutWidget = QWidget(regForm)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(100, 3, 251, 171))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.regLine_user = QLineEdit(self.verticalLayoutWidget)
        self.regLine_user.setObjectName(u"regLine_user")
        self.verticalLayout.addWidget(self.regLine_user)
        self.regLine_pw = QLineEdit(self.verticalLayoutWidget)
        self.regLine_pw.setObjectName(u"regLine_pw")
        self.regLine_pw.setEchoMode(QLineEdit.EchoMode.Password)
        self.verticalLayout.addWidget(self.regLine_pw)
        self.regLine_repw = QLineEdit(self.verticalLayoutWidget)
        self.regLine_repw.setObjectName(u"regLine_repw")
        self.regLine_repw.setEchoMode(QLineEdit.EchoMode.Password)
        self.verticalLayout.addWidget(self.regLine_repw)
        self.horizontalLayoutWidget = QWidget(regForm)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(100, 173, 251, 41))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.reg_clearButton = QPushButton(self.horizontalLayoutWidget)
        self.reg_clearButton.setObjectName(u"reg_clearButton")
        self.horizontalLayout.addWidget(self.reg_clearButton)
        self.reg_saveButton = QPushButton(self.horizontalLayoutWidget)
        self.reg_saveButton.setObjectName(u"reg_saveButton")
        self.horizontalLayout.addWidget(self.reg_saveButton)
        self.reg_label_1 = QLabel(regForm)
        self.reg_label_1.setObjectName(u"reg_label_1")
        self.reg_label_1.setGeometry(QRect(18, 28, 71, 20))
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(10)
        self.reg_label_1.setFont(font)
        self.reg_label_1.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.reg_label_2 = QLabel(regForm)
        self.reg_label_2.setObjectName(u"reg_label_2")
        self.reg_label_2.setGeometry(QRect(18, 78, 71, 20))
        self.reg_label_2.setFont(font)
        self.reg_label_2.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.reg_label_3 = QLabel(regForm)
        self.reg_label_3.setObjectName(u"reg_label_3")
        self.reg_label_3.setGeometry(QRect(2, 128, 87, 20))
        self.reg_label_3.setFont(font)
        self.reg_label_3.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.reg_label_4 = QLabel(regForm)
        self.reg_label_4.setObjectName(u"reg_label_4")
        self.reg_label_4.setGeometry(QRect(29, 223, 61, 20))
        font1 = QFont()
        font1.setFamilies([u"Arial"])
        font1.setPointSize(10)
        font1.setBold(True)
        self.reg_label_4.setFont(font1)
        self.reg_label_4.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.reg_label_status = QLabel(regForm)
        self.reg_label_status.setObjectName(u"reg_label_status")
        self.reg_label_status.setGeometry(QRect(100, 223, 251, 20))
        self.reg_label_status.setFont(font1)
        self.reg_label_status.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.reg_label_status.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.retranslateUi(regForm)

        QMetaObject.connectSlotsByName(regForm)
    # setupUi

    def retranslateUi(self, regForm):
        regForm.setWindowTitle(QCoreApplication.translate("regForm", u"Register Form", None))
        self.reg_clearButton.setText(QCoreApplication.translate("regForm", u"Clear", None))
        self.reg_saveButton.setText(QCoreApplication.translate("regForm", u"Save", None))
        self.reg_label_1.setText(QCoreApplication.translate("regForm", u"Username", None))
        self.reg_label_2.setText(QCoreApplication.translate("regForm", u"Password", None))
        self.reg_label_3.setText(QCoreApplication.translate("regForm", u"Re-Password", None))
        self.reg_label_4.setText(QCoreApplication.translate("regForm", u"Status :", None))
        self.reg_label_status.setText("")
    # retranslateUi