from PyQt6.QtCore import (QCoreApplication, QMetaObject, QRect)
from PyQt6.QtGui import (QFont, QIcon)
from PyQt6.QtWidgets import (QComboBox, QFrame,QLabel, QLineEdit, QPushButton,
                             QTabWidget, QTableWidget, QTableWidgetItem, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(818, 537)
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ContactNew))
        Form.setWindowIcon(icon)
        self.tabWidget = QTabWidget(Form)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 820, 541))
        self.kTab = QWidget()
        self.kTab.setObjectName(u"kTab")
        self.result = QLabel(self.kTab)
        self.result.setObjectName(u"result")
        self.result.setGeometry(QRect(70, 490, 171, 16))
        self.saveButton = QPushButton(self.kTab)
        self.saveButton.setObjectName(u"saveButton")
        self.saveButton.setGeometry(QRect(692, 480, 100, 30))
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentSave))
        self.saveButton.setIcon(icon1)
        self.accountinf = QFrame(self.kTab)
        self.accountinf.setObjectName(u"accountinf")
        self.accountinf.setGeometry(QRect(0, 20, 791, 161))
        self.accountinf.setFrameShape(QFrame.Shape.StyledPanel)
        self.accountinf.setFrameShadow(QFrame.Shadow.Raised)
        self.ckodu_line = QLineEdit(self.accountinf)
        self.ckodu_line.setObjectName(u"ckodu_line")
        self.ckodu_line.setGeometry(QRect(80, 11, 231, 22))
        self.cadi_line = QLineEdit(self.accountinf)
        self.cadi_line.setObjectName(u"cadi_line")
        self.cadi_line.setGeometry(QRect(80, 50, 231, 22))
        self.csektor_line = QLineEdit(self.accountinf)
        self.csektor_line.setObjectName(u"csektor_line")
        self.csektor_line.setGeometry(QRect(80, 90, 231, 22))
        self.ckodu_label = QLabel(self.accountinf)
        self.ckodu_label.setObjectName(u"ckodu_label")
        self.ckodu_label.setGeometry(QRect(10, 11, 61, 16))
        self.cadi_label = QLabel(self.accountinf)
        self.cadi_label.setObjectName(u"cadi_label")
        self.cadi_label.setGeometry(QRect(10, 50, 49, 16))
        self.csektor_label = QLabel(self.accountinf)
        self.csektor_label.setObjectName(u"csektor_label")
        self.csektor_label.setGeometry(QRect(10, 90, 49, 16))
        self.dc_label = QLabel(self.accountinf)
        self.dc_label.setObjectName(u"dc_label")
        self.dc_label.setGeometry(QRect(10, 130, 61, 16))
        self.isatis_label = QLabel(self.accountinf)
        self.isatis_label.setObjectName(u"isatis_label")
        self.isatis_label.setGeometry(QRect(450, 50, 49, 16))
        self.asatis_line = QLineEdit(self.accountinf)
        self.asatis_line.setObjectName(u"asatis_line")
        self.asatis_line.setGeometry(QRect(520, 11, 231, 22))
        self.isatis_line = QLineEdit(self.accountinf)
        self.isatis_line.setObjectName(u"isatis_line")
        self.isatis_line.setGeometry(QRect(520, 50, 231, 22))
        self.asatis_label = QLabel(self.accountinf)
        self.asatis_label.setObjectName(u"asatis_label")
        self.asatis_label.setGeometry(QRect(450, 11, 61, 16))
        self.vade_label = QLabel(self.accountinf)
        self.vade_label.setObjectName(u"vade_label")
        self.vade_label.setGeometry(QRect(180, 130, 51, 20))
        self.vade_line = QLineEdit(self.accountinf)
        self.vade_line.setObjectName(u"vade_line")
        self.vade_line.setGeometry(QRect(240, 130, 71, 22))
        self.satinalma_line = QLineEdit(self.accountinf)
        self.satinalma_line.setObjectName(u"satinalma_line")
        self.satinalma_line.setGeometry(QRect(520, 90, 231, 22))
        self.email_line = QLineEdit(self.accountinf)
        self.email_line.setObjectName(u"email_line")
        self.email_line.setGeometry(QRect(520, 129, 231, 22))
        self.email_label = QLabel(self.accountinf)
        self.email_label.setObjectName(u"email_label")
        self.email_label.setGeometry(QRect(450, 129, 49, 16))
        self.satinalma_label = QLabel(self.accountinf)
        self.satinalma_label.setObjectName(u"satinalma_label")
        self.satinalma_label.setGeometry(QRect(450, 90, 61, 16))
        self.dc_box = QComboBox(self.accountinf)
        self.dc_box.addItem("")
        self.dc_box.addItem("")
        self.dc_box.addItem("")
        self.dc_box.setObjectName(u"dc_box")
        self.dc_box.setGeometry(QRect(80, 127, 75, 25))
        self.label = QLabel(self.kTab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 186, 111, 20))
        font = QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(True)
        self.label.setFont(font)
        self.durum = QLabel(self.kTab)
        self.durum.setObjectName(u"durum")
        self.durum.setGeometry(QRect(10, 490, 61, 16))
        self.address = QFrame(self.kTab)
        self.address.setObjectName(u"address")
        self.address.setGeometry(QRect(0, 210, 791, 251))
        self.address.setFrameShape(QFrame.Shape.StyledPanel)
        self.address.setFrameShadow(QFrame.Shadow.Raised)
        self.addr_line = QLineEdit(self.address)
        self.addr_line.setObjectName(u"addr_line")
        self.addr_line.setGeometry(QRect(80, 11, 671, 22))
        self.addr_label = QLabel(self.address)
        self.addr_label.setObjectName(u"addr_label")
        self.addr_label.setGeometry(QRect(10, 13, 61, 16))
        self.province_line = QLineEdit(self.address)
        self.province_line.setObjectName(u"province_line")
        self.province_line.setGeometry(QRect(80, 50, 161, 22))
        self.province_label = QLabel(self.address)
        self.province_label.setObjectName(u"province_label")
        self.province_label.setGeometry(QRect(10, 52, 61, 16))
        self.district_label = QLabel(self.address)
        self.district_label.setObjectName(u"district_label")
        self.district_label.setGeometry(QRect(265, 52, 61, 16))
        self.district_line = QLineEdit(self.address)
        self.district_line.setObjectName(u"district_line")
        self.district_line.setGeometry(QRect(335, 50, 161, 22))
        self.country_label = QLabel(self.address)
        self.country_label.setObjectName(u"country_label")
        self.country_label.setGeometry(QRect(520, 52, 61, 16))
        self.country_line = QLineEdit(self.address)
        self.country_line.setObjectName(u"country_line")
        self.country_line.setGeometry(QRect(590, 50, 161, 22))
        self.mmail_label = QLabel(self.address)
        self.mmail_label.setObjectName(u"mmail_label")
        self.mmail_label.setGeometry(QRect(10, 90, 61, 16))
        self.mmail_line = QLineEdit(self.address)
        self.mmail_line.setObjectName(u"mmail_line")
        self.mmail_line.setGeometry(QRect(80, 90, 231, 22))
        self.mobil_line = QLineEdit(self.address)
        self.mobil_line.setObjectName(u"mobil_line")
        self.mobil_line.setGeometry(QRect(80, 170, 231, 22))
        self.mobil_label = QLabel(self.address)
        self.mobil_label.setObjectName(u"mobil_label")
        self.mobil_label.setGeometry(QRect(10, 170, 61, 16))
        self.tel_line = QLineEdit(self.address)
        self.tel_line.setObjectName(u"tel_line")
        self.tel_line.setGeometry(QRect(80, 130, 231, 22))
        self.tel_label = QLabel(self.address)
        self.tel_label.setObjectName(u"tel_label")
        self.tel_label.setGeometry(QRect(10, 130, 61, 16))
        self.fax_label = QLabel(self.address)
        self.fax_label.setObjectName(u"fax_label")
        self.fax_label.setGeometry(QRect(10, 210, 61, 16))
        self.fax_line = QLineEdit(self.address)
        self.fax_line.setObjectName(u"fax_line")
        self.fax_line.setGeometry(QRect(80, 210, 231, 22))
        self.iban_label = QLabel(self.address)
        self.iban_label.setObjectName(u"iban_label")
        self.iban_label.setGeometry(QRect(340, 210, 61, 16))
        self.vno_line = QLineEdit(self.address)
        self.vno_line.setObjectName(u"vno_line")
        self.vno_line.setGeometry(QRect(420, 130, 331, 22))
        self.bank_label = QLabel(self.address)
        self.bank_label.setObjectName(u"bank_label")
        self.bank_label.setGeometry(QRect(340, 170, 61, 16))
        self.iban_line = QLineEdit(self.address)
        self.iban_line.setObjectName(u"iban_line")
        self.iban_line.setGeometry(QRect(420, 210, 331, 22))
        self.vno_label = QLabel(self.address)
        self.vno_label.setObjectName(u"vno_label")
        self.vno_label.setGeometry(QRect(340, 130, 61, 16))
        self.vd_line = QLineEdit(self.address)
        self.vd_line.setObjectName(u"vd_line")
        self.vd_line.setGeometry(QRect(420, 90, 331, 22))
        self.bank_line = QLineEdit(self.address)
        self.bank_line.setObjectName(u"bank_line")
        self.bank_line.setGeometry(QRect(420, 170, 331, 22))
        self.vd_label = QLabel(self.address)
        self.vd_label.setObjectName(u"vd_label")
        self.vd_label.setGeometry(QRect(340, 90, 71, 16))
        self.label_2 = QLabel(self.kTab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 0, 111, 16))
        font1 = QFont()
        font1.setPointSize(11)
        font1.setUnderline(True)
        self.label_2.setFont(font1)
        self.clearButton = QPushButton(self.kTab)
        self.clearButton.setObjectName(u"clearButton")
        self.clearButton.setGeometry(QRect(585, 480, 100, 30))
        icon2 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentNew))
        self.clearButton.setIcon(icon2)
        self.tabWidget.addTab(self.kTab, "")
        self.rTab = QWidget()
        self.rTab.setObjectName(u"rTab")
        self.tableWidget = QTableWidget(self.rTab)
        if (self.tableWidget.columnCount() < 10):
            self.tableWidget.setColumnCount(10)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, __qtablewidgetitem9)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(10, 10, 791, 471))
        self.refresh = QPushButton(self.rTab)
        self.refresh.setObjectName(u"refresh")
        self.refresh.setGeometry(QRect(691, 480, 100, 30))
        icon3 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ViewRefresh))
        self.refresh.setIcon(icon3)
        self.silButton = QPushButton(self.rTab)
        self.silButton.setObjectName(u"silButton")
        self.silButton.setGeometry(QRect(585, 480, 100, 30))
        icon4 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditDelete))
        self.silButton.setIcon(icon4)
        self.tabWidget.addTab(self.rTab, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Cari Kartı", None))
        self.result.setText("")
        self.saveButton.setText(QCoreApplication.translate("Form", u"Kaydet", None))
        self.ckodu_label.setText(QCoreApplication.translate("Form", u"Cari Kodu", None))
        self.cadi_label.setText(QCoreApplication.translate("Form", u"Cari Ad\u0131", None))
        self.csektor_label.setText(QCoreApplication.translate("Form", u"Sekt\u00f6r\u00fc", None))
        self.dc_label.setText(QCoreApplication.translate("Form", u"D\u00f6viz Cinsi", None))
        self.isatis_label.setText(QCoreApplication.translate("Form", u"\u0130\u00e7 Sat\u0131\u015f", None))
        self.asatis_label.setText(QCoreApplication.translate("Form", u"Alan Sat\u0131\u015f", None))
        self.vade_label.setText(QCoreApplication.translate("Form", u"Vade", None))
        self.email_label.setText(QCoreApplication.translate("Form", u"E-Posta", None))
        self.satinalma_label.setText(QCoreApplication.translate("Form", u"Sat\u0131nalma", None))
        self.dc_box.setItemText(0, QCoreApplication.translate("Form", u"TL", None))
        self.dc_box.setItemText(1, QCoreApplication.translate("Form", u"USD", None))
        self.dc_box.setItemText(2, QCoreApplication.translate("Form", u"EURO", None))
        self.label.setText(QCoreApplication.translate("Form", u"\u0130leti\u015fim Bilgisi", None))
        self.durum.setText(QCoreApplication.translate("Form", u"Durum :", None))
        self.addr_label.setText(QCoreApplication.translate("Form", u"Adres", None))
        self.province_label.setText(QCoreApplication.translate("Form", u"\u0130l", None))
        self.district_label.setText(QCoreApplication.translate("Form", u"\u0130l\u00e7e", None))
        self.country_label.setText(QCoreApplication.translate("Form", u"\u00dclke", None))
        self.mmail_label.setText(QCoreApplication.translate("Form", u"Muh. Mail", None))
        self.mobil_label.setText(QCoreApplication.translate("Form", u"Mobil", None))
        self.tel_label.setText(QCoreApplication.translate("Form", u"Telefon", None))
        self.fax_label.setText(QCoreApplication.translate("Form", u"Fax", None))
        self.iban_label.setText(QCoreApplication.translate("Form", u"IBAN No", None))
        self.bank_label.setText(QCoreApplication.translate("Form", u"Banka Ad\u0131", None))
        self.vno_label.setText(QCoreApplication.translate("Form", u"Vergi No", None))
        self.vd_label.setText(QCoreApplication.translate("Form", u"Vergi Dairesi", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Cari Bilgisi", None))
        self.clearButton.setText(QCoreApplication.translate("Form", u"Temizle", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.kTab), QCoreApplication.translate("Form", u"Kay\u0131t", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("Form", u"Kodu", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("Form", u"Ad\u0131", None));
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("Form", u"Sekt\u00f6r", None));
        ___qtablewidgetitem3 = self.tableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("Form", u"D\u00f6viz Cinsi", None));
        ___qtablewidgetitem4 = self.tableWidget.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("Form", u"Vade", None));
        ___qtablewidgetitem5 = self.tableWidget.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("Form", u"Alan Sat\u0131\u015f", None));
        ___qtablewidgetitem6 = self.tableWidget.horizontalHeaderItem(6)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("Form", u"\u0130\u00e7 Sat\u0131\u015f", None));
        ___qtablewidgetitem7 = self.tableWidget.horizontalHeaderItem(7)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("Form", u"Sat\u0131nalma", None));
        ___qtablewidgetitem8 = self.tableWidget.horizontalHeaderItem(8)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("Form", u"E-Posta", None));
        ___qtablewidgetitem9 = self.tableWidget.horizontalHeaderItem(9)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("Form", u"Mobil", None));
        self.refresh.setText(QCoreApplication.translate("Form", u"Yenile", None))
        self.silButton.setText(QCoreApplication.translate("Form", u"Sil", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rTab), QCoreApplication.translate("Form", u"Liste", None))
    # retranslateUi